### ISSUE TITLE
TMA吸附在Cu111上时，吸附构型有问题

### ISSUE THREAD

**Issue by haojieli-code** [stanfordbshan/HTMACat-kit#34]
## 你使用的 HTMACat 是什么版本，什么环境？

> HTMACat 版本: 1.0.3
>
> 环境: python 3.8 in windows 
>

## 你遇到什么问题了？

> Cu111上吸附TMA的时候，TMA的三个C是C-C-C连接，而不是三个甲基和Al原子连接
```yaml
StrucInfo:
  element: Cu
  lattype: fcc
  latcont: 3.58
  facet: ['111']
  dope:
    Cu: [0]

Model:
  SML: True
  ads:
    - ['C[Al](C)C',1]
```
## 产生的POSCAR结构

> 
![image](https://user-images.githubusercontent.com/77005205/233008128-bf6f4cb7-f029-4d3c-8f13-005351dc8dba.png)

## 你期望的结果

> 三个甲基和Al原子相连
